### ISSUE TITLE
build-fs-tree dependency out of date

### ISSUE THREAD

**Issue by michel-slm** [olson-sean-k/wax#43]
Please consider updating build-fs-tree from 0.3.0 to 0.6.0:

https://crates.io/crates/build-fs-tree/

Unfortunately upstream does not seem to provide a changelog so it's hard to say how much code modification is needed.

**Comment by olson-sean-k** [comment]
The dependency on `build-fs-tree` has been upgraded to `^0.6.0` in e45553a. I'll leave this open until a release with the new dependency specification has been published.

**Comment by olson-sean-k** [comment]
Fixed in version `0.6.0` (1afcda8).
