### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by milesj** [olson-sean-k/wax#45]
Hello @olson-sean-k  👋 

I'm a big fan of this crate, I believe it to be the best glob crate that currently exists.

However, I've noticed there's been no updates in over a year, and was wondering if this is still maintained. I'm well aware of how much time/cost maintaining projects takes, so understandable if you're busy.

At minimum, it would be great to at least get dependency upgrades (like miette). Would you be open to collaborators?

Cheers!

**Comment by olson-sean-k** [comment]
I'm happy to hear that you like this crate!

I had less time for Wax not too long after the `0.5.0` release so there was a bit of a lull in its development. That being said, I am still happy to maintain it and have actually been working on a large refactor in a separate experimental repository for some time now! I think I've spent too much time on that at this point though. There are at least two PRs that I think would be really great to address and get into a `0.6.0` release ahead of any refactoring along with basic maintenance like dependency upgrades.

I'm hoping to turn my attention to that very soon. Please stay tuned!

**Comment by milesj** [comment]
Sounds great, looking forward to it! Thanks for all the work.

**Comment by ErichDonGubler** [comment]
I would also like to register my enjoyment of this crate. As somebody who makes a career of maintaining open-source cross-platform tools, it's very nice to have a globbing abstraction that has had so much portability and thought. 🙂

**Comment by olson-sean-k** [comment]
I've just published version `0.6.0` (1afcda8). 🎉 Some things of note about this release:

- Dependencies and MSRV have been upgraded.
- Diagnostic APIs have been factored out into a separate (optional) dependency.
- Errors always clone any necessary data and have no lifetime parameters.
- Diagnostic features are no longer required to get basic location information for `BuildError`s.
- `Glob` implements `Display`.

Now that `0.6.0` has been published, I'll go ahead and close this issue. There's a lot more to do!

**Comment by milesj** [comment]
Amazing, thank you!
